Update php-cs-fixer and its config and fix the codebase
jolicode/secret-santa pull request #229
Opened 2021-12-01 14:42 UTC by lyrixx

2021-12-01 15:54 UTC, pyrech requested changes

2021-12-01 15:54 UTC, pyrech commented on src/Controller/ZoomController.php
> +            // Check given state against previously stored one to mitigate CSRF attack
I guess this comment should be moved above the following if

2021-12-01 15:54 UTC, pyrech commented on src/Zoom/MessageSender.php
> +    public const GIFT_EMOJI = "\xF0\x9F\x8E\x81";
those constants can be made private IIRC

2021-12-01 15:54 UTC, pyrech commented on src/Discord/ApiHelper.php
> +    public const TOKEN_TYPE_BOT = 'Bot';
constant can be private

2021-12-01 16:09 UTC, lyrixx commented
@pyrech thanks for the review, I addressed your comments.

2021-12-02 15:42 UTC, pyrech approved these changes

2021-12-02 15:42 UTC, merged